services:
  training-mlflow:
    container_name: training-container
    build:
      context: .
    volumes:
      - /opt/data:/opt/data
      - ../../mlartifacts:/opt/code/models/mlartifacts
      - ../../mlruns:/opt/code/models/mlruns
    ports:
      - 8509:8090
    restart: on-failure
