channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==2.2.1
  - numpy==1.26.4
  - pandas==2.2.2
  - torch==2.2.2
  - tqdm==4.66.5
name: mlflow-env
