active_stack_id: 97aa081a-1ad0-433d-aefd-758719f17bc7
active_workspace_name: default
analytics_opt_in: true
store:
  backup_directory: /Users/ilia/learning_ds/F24/mlopls-pmldl/services/zenml/pipelines/services/zenml/database_backup
  backup_strategy: in-memory
  database: /Users/ilia/learning_ds/F24/mlopls-pmldl/services/zenml/pipelines/services/zenml/local_stores/default_zen_store/zenml.db
  driver: sqlite
  max_overflow: 20
  pool_pre_ping: true
  pool_size: 20
  secrets_store:
    type: sql
  ssl_verify_server_cert: false
  type: sql
  url: sqlite:////Users/ilia/learning_ds/F24/mlopls-pmldl/services/zenml/pipelines/services/zenml/local_stores/default_zen_store/zenml.db
user_id: 2fe4b0f7-0728-475b-b00b-9e20ec918595
version: 0.66.0
