services:
  fastapi:
    container_name: api-container
    build:
      context: ./api
    ports:
      - 8000:8000
    volumes:
      - ./models:/models
    environment:
      - MODELS_NAME=best.pt
      - MODEL_VERSION=1
    networks:
      - interserver

  streamlit:
    container_name: webapp-container
    build:
      context: ./app
    ports:
      - 8501:8501
    environment:
      - FASTAPI_URL=http://api-container:8000/main
    depends_on:
      - fastapi
    networks:
      - interserver

networks:
  interserver:
    driver: bridge
