services:
  fastapi:
    container_name: api-container
    build:
      context: ./api
    ports:
      - 8501:8000
    environment:
      - MODELS_NAME=basic_model
      - MODEL_ALIAS=production
      - MLFLOW_URL=http://mlflow-container:8080
    networks:
      - interserver
    depends_on:
      - mlflow

  streamlit:
    container_name: webapp-container
    build:
      context: ./app
    ports:
      - 8500:8501
    environment:
      - FASTAPI_URL=http://fastapi:8000/main
    depends_on:
      - fastapi
    networks:
      - interserver

  mlflow:
    container_name: mlflow-container
    build:
      context: ./mlflow_api
    ports:
      - 8502:8080
    networks:
      - interserver
    

networks:
  interserver:
    driver: bridge
