services:
  airflow:
    container_name: "airflow_service"
    build:
      context: .
      dockerfile: airflow.Dockerfile
    restart: always
    environment:
      AIRFLOW_HOME: /project/services/airflow
      # The directories of source code and scripts in the project
      # These locations will be added to let airflow see our files
      PYTHONPATH: /project/src:/project/scripts
      # A custom environment variable to our project directory
      PROJECTPATH: /project
    # Allows to create volumes
    volumes:
      # Creates a volume for airflow metadata
      - ./services/airflow:/opt/airflow
      # Creates a volume to store the project in the container
      - .:/project
    ports:
      - 8080:8080